services:
  app-dev:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - .env.development.local
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    profiles:
      - dev
    networks:
      - app-network

  db:
    image: postgres:17-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_password
      - POSTGRES_DB=local_db
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
